# Generated by Django 5.0.6 on 2024-07-01 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=55)),
                ('event_venue', models.CharField(max_length=100)),
                ('event_time', models.DateField(default=django.utils.timezone.now)),
                ('event_organizer', models.CharField(default='Elite Sports Club', max_length=100)),
                ('event_description', models.TextField()),
            ],
        ),
    ]
