# Generated by Django 5.0.6 on 2024-07-02 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_time', models.TimeField(default=django.utils.timezone.now)),
                ('notice_by', models.CharField(default='Elite Sports Club', max_length=100)),
                ('notice_description', models.TextField()),
            ],
        ),
    ]
