# Generated by Django 5.0.6 on 2024-07-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0004_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
