# Generated by Django 5.0.6 on 2024-07-08 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0005_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(default='null', max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('male', 'male'), ('female', 'female')], max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='club_app/member_pictures')),
            ],
        ),
    ]
