# Generated by Django 5.0.6 on 2024-07-10 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0006_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('about_user', models.TextField(default='')),
                ('user_cv', models.ImageField(blank=True, null=True, upload_to='club_app/user_cv')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
