# Generated by Django 5.0.6 on 2024-07-12 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0007_user_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('question', models.TextField(max_length=200)),
                ('question_date', models.DateField(default=django.utils.timezone.now)),
                ('answer', models.TextField(default='')),
                ('answer_date', models.DateField(default='null')),
            ],
        ),
    ]
