# Generated by Django 5.0.6 on 2024-07-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0008_query_doubt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query_Doubt',
        ),
    ]
