# Generated by Django 6.0.3 on 2026-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0010_query_doubt'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sports',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
