# Generated by Django 6.0.3 on 2026-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0011_member_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
