# Generated by Django 6.0.3 on 2026-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0012_member_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
