# Generated by Django 6.0.3 on 2026-04-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0013_member_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_pic',
            field=models.ImageField(default='', upload_to='coach_pics/'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
