# Generated by Django 6.0.3 on 2026-04-11 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0014_alter_coach_coach_pic_alter_coach_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.CharField(max_length=50)),
                ('coach_name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.CharField(max_length=50)),
                ('coach_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('sport', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(default='1 Hour', max_length=50)),
                ('location', models.CharField(default='Club Ground', max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
