# Generated by Django 6.0.3 on 2026-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0015_announcement_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscription_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_duration',
            field=models.CharField(blank=True, choices=[('1 Month', '1 Month'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year')], max_length=20, null=True),
        ),
    ]
